# Generated by Django 5.2.1 on 2025-05-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=40)),
                ('stream_url', models.URLField()),
                ('dial', models.CharField(max_length=10)),
            ],
        ),
    ]
