# Generated by Django 5.2.5 on 2026-01-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coclea', '0002_remove_estacionradio_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeMuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('mensaje', models.TextField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
