# Generated by Django 5.2.5 on 2026-01-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coclea', '0003_mensajemuro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajemuro',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
